CONDICIONES DE BUSQUEDA (WHERE)EN CONSULTAS SIMPLES Y CONSULTA MULTITABLA
1)TEST RANGO(BETWEEN)
2) TEST DE COMPARACION
3) TEST DE PERTENECIA A CONJUNTO(IN,NOT IN)
4) TEST VALOR NULO
5) TEST DE CORRESPONDENCIA CON UN PATRON (LIKE,NOT )

SUBCONSULTAS
LENGUAJE SQL UTILIZAR EL RESULTADO DE UNA CONSULTA COMO PARTE DE OTRA CONSULTA 
LAS SUBCONSULTAS DEBEN IR ENTRE PARENTESIS
LAS SUBCONSULTAS SE PUEDE UTILIZAR DESPUES DE LA CLAUSULA WHERE O DESPUES DE LA CLAUSULA HAVING		
LAS CONSULTAS PERMITEN DESCOMPONER UNA CONSULTA	EN PARTES Y POSTERIORMENTE COMPONER ESAS PARTES

---LISTAR LOS NOMBRES DE LOS VENDEDORES CUYA EDAD SEA MAYOR AL PROMEDIO
	SELECT	AVG(EDAD) FROM REPVENTAS
		SELECT	*FROM REPVENTAS


		SELECT NOMBRE,EDAD 
		FROM REPVENTAS
		WHERE EDAD	> (SELECT AVG(EDAD) FROM REPVENTAS)

---LISTAR LAS OFICINAS EN DONDE EL OBJETIVO DE VENTAS DE LA	OFICINA EXCEDEN A LA 
---SUMA DE LAS CUOTAS DE LOS VENDEDORES INDIVIDUALES
SELECT CIUDAD,OBJETIVO
FROM OFICINAS 
WHERE OBJETIVO > (SELECT SUM(CUOTA) FROM REPVENTAS
					WHERE OFICINA  = OFICINA_REP )

CONDICIONES DE BUSQUEDAS EN SUBCONSULTAS 
1)TEST DE COMPARACION DE SUBCONSULTAS 
=, >, >=, <, <=, <> O !=
LA SUBCONSULTA DEBE DEVOLVER UN UNICO VALOR (UNA SOLA FILA Y UNA SOLA COLUMNA)
--LISTAR LOS VENDEDORES CUYAS CUOTAS SON IGUALES O SUPERIORES AL OBJETIVO DE VENTAS DE ATLANTA
SELECT NOMBRE,CUOTA
FROM REPVENTAS
WHERE CUOTA >=(SELECT OBJETIVO FROM OFICINAS 
				WHERE CIUDAD = 'ATLANTA' )

---LISTAR TODOS LOS PRODUCTOS DEL FABRICANTE ACI PARA LAS CUALES LAS EXISTENCIAS 
---SUPERAN A LAS EXISTENCIAS  DEL PRODUCTO ACI-41004

SELECT DESCRIPCION,EXISTENCIAS 
FROM PRODUCTOS
WHERE ID_FAB = 'ASI'
AND EXISTENCIAS > (SELECT EXISTENCIAS FROM PRODUCTOS
					WHERE ID_FAB = 'ACI'
					AND ID_PRODUCTO ='41004')

--TEST DE PERTINENCIA A CONJUNTO SUBCONSULTA(IN,NOT IN)
--LISTAR LOS VENDEDORES QUE TRABAJAN EN OFICINAS CUYAS VENTAS SUPERAN SU OBJETIVO

SELECT NOMBRE,OFICINA_REP
FROM REPVENTAS
WHERE OFICINA_REP IN (SELECT OFICINA FROM OFICINAS 
					   WHERE VENTAS > OBJETIVO )


--LISTAR LOS VENDEDORES  QUE NO TRABAJAN EN OFICINAS DIRIGIDAS POR LARRY FICH (EMPLEADO 108)
SELECT NOMBRE,OFICINA_REP
FROM REPVENTAS
WHERE OFICINA_REP IN ( SELECT OFICINA FROM OFICINAS
						WHERE DIR = 108)


---LISTAR TODOS LOS CLIENTES QUE HAN PERMITIDO PEDIDOS DEL FABRICANTE ACI
---(NUMEROS DE PRODUCTOS QUE COMIENZAN CON 4100) ENTRE ENERO Y JUNIO DE 1990

SELECT EMPRESA
FROM CLIENTES 
WHERE NUM_CLIE IN(SELECT CLIE FROM PEDIDOS 
				  WHERE FAB = 'ACI'
				  AND PRODUCTO LIKE '4100%'
				  AND FECHA_PEDIDO BETWEEN
				   AND FECHA_PEDIDO BETWEEN '01/01/1990' AND '30/06/1990')

---TEST DE EXISTENCIA(EXITS, NOT EXITS)
SELECT *FROM REPVENTAS
SELECT DISTINCT REP FROM PEDIDOS
SELECT REP FROM PEDIDOS
ORDER BY REP


SELECT NUM_EMPL,NOMBRE 
FROM REPVENTAS
WHERE NOT EXISTS 
(SELECT *FROM PEDIDOS
		WHERE NUM_EMPL = REP )

		SELECT NUM_EMPL,NOMBRE 
FROM REPVENTAS
WHERE EXISTS 
(SELECT *FROM PEDIDOS
		WHERE NUM_EMPL = REP )

---CONSULTAR LOS PRODUCTOS QUE SE HAYAN PEDIDO (COMPRANDO)
SELECT DESCRIPCION 
FROM PRODUCTOS
WHERE EXISTS 
(SELECT *FROM PEDIDOS
		WHERE ID_FAB = FAB
		AND ID_PRODUCTO = PRODUCTO )

		--LISTAR LOS PRODUCTOS PARA LOS CUALES SE HA RECIBIDO UN PEDIDO DE 25000 O MAS

		SELECT DESCRIPCION 
FROM PRODUCTOS
WHERE EXISTS 
(SELECT *FROM NUM_PEDIDO,FECHA_PEDIDO,IMPORTE FROM PEDIDOS
WHERE ID_FAB = FAB
AND ID_PRODUCTO = PRODUCTO
AND IMPORTE >25000


---LISTAR LOS CLIENTES ASIGNADOS A SUE SMITH QUE NO HAN PERMITIDO UN PEDIDO MAYOR A 30000
SELECT EMPRESA 
FROM CLIENTES 
WHERE  REP_CLIE IN (SELECT NUM_EMPL FROM REPVENTAS
WHERE NOMBRE = 'SUE SMITH')
AND NOT EXISTS(SELECT *FROM PEDIDOS
WHERE IMPORTE >30000
AND NUM_CLIE = CLIE)

--- TEST CUANTIFICADOS (ANY (ALGUNOS),ALL(TODOS))

--LISTAR LOS VENDEDORES QUE HAN ACEPTADO UN PEDIDO QUE REPRESENTA MAS DEL 10% DE SUS CUOTAS 
SELECT OFICINAS FROM OFICINAS 
WHERE REGION ='ESTE'

SELECT NOMBRE 
FROM REPVENTAS 
WHERE OFICINA_REP = ANY(SELECT OFICINA FROM OFICINAS 
WHERE = 'ESTE')


SELECT EDAD,TITULO FROM REPVENTAS

SELECT NOMBRE,EDAD
FROM REPVENTAS 
WHERE EDAD > ANY (SELECT EDAD FROM REPVENTAS 
WHERE TITULO = 'DIR VENTAS')



SELECT NOMBRE,EDAD
FROM REPVENTAS 
WHERE EDAD > ALL (SELECT EDAD FROM REPVENTAS 
WHERE TITULO = 'DIR VENTAS')



UPDATE REPVENTAS SET EDAD = 29
WHERE NOMBRE = 'PAUL CRUZ'



---LISTAR LOS VENDEDORES QUE HAN ACEPTADO UN PEDIDO QUE REPRESENTA MAS DEL 10%

SELECT NUM_EMPL,NOMBRE,CUOTA,(CUOTA * 0.10) 
FROM REPVENTAS 
WHERE (CUOTA * 0.10) < ANY (SELECT IMPORTE FROM PEDIDOS
							WHERE NUM_EMPL = REP )


---1) ELIMINAR TODOS LOS PEDIDOS DE CLIENTE (NUMERO DE CLIENTE 2117)

SELECT *FROM PEDIDOS
WHERE CLIE = 2117

DELETE FROM PEDIDOS
WHERE CLIE = 2117

--2) ELIMINAR LOS PEDIDOS REALIZADOS ANTES DEL 15 DE NOVIEMBRE DE 1989

SELECT *FROM PEDIDOS
WHERE FECHA_PEDIDO < '15/11/1989'

DELETE FROM PEDIDOS
WHERE FECHA_PEDIDO < '15/11/1989'

--3) SUPRIMIR TODAS LAS FILAS CORRESPONDIENTES A LOS CLIENTES ATENDIDOS POR BILL ADAMS
-- MARY JONES O DAN ROBERTH (NUMERO DE EMPLEADO 105,109 O 101)


SELECT *FROM CLIENTES 
WHERE REP_CLIE IN(105,109,101)



--4) ELIMINAR TODOS LOS PEDIDOS
SELECT *FROM PEDIDOS 

DELETE FROM PEDIDOS
